import './globals.css'
import { Inter } from 'next/font/google'
import Nav from './Nav'
import Footer from './Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'MovieSpace',
  description: 'Generated by create next app | TMDB API',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;500&display=swap" rel="stylesheet"/>
        <Nav/>
        {children}
      </body>
    </html>
  )
}
