"use client"
import './globals.css'
import CategoryWrapper from './CategoryWrapper'
import { useState, useEffect, useRef } from 'react'
import "./sass/Nav.scss"
import Link from 'next/link'


export const metadata = {
  title: 'MovieSpace',
  description: 'Generated by create next app | TMDB API',
}

export default function RootLayout({ children }) {

  const [genres, showGenres] = useState(false)


  return (
    <html lang="en">
      <body>
      <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;500&display=swap" rel="stylesheet"/>
        

        <div className='nav-container'>
          <div className='nav-wrapper'>
            <Link className='logo' href="/"><p>MovieSpace</p></Link>
            <button  onClick={() =>  showGenres(!genres) } className='category' href="./category">Genres</button>
          </div>
        </div>


        {genres && <CategoryWrapper/>}
        {children}
      </body>
    </html>
  )
}
